redesign explore pages
Jinwoo-1162/Buzzer pull request #28
Opened 2022-11-27 03:11 UTC by Sherwin6180

redesign explore pages

2022-11-27 10:05 UTC, Jinwoo-1162 requested changes
When defining width, use a relative unit like em, rem, vw, etc instead of a constant unit like px to account for different screen sizes

Curious why you removed the variable background value for a hard coded one

2022-11-27 14:44 UTC, Sherwin6180 commented
> When defining width, use a relative unit like em, rem, vw, etc instead of a constant unit like px to account for different screen sizes
> 
> Curious why you removed the variable background value for a hard coded one

(1) Because in Timeline.css, the width is defined to be 700px.
(2) Because I like the shaded search box.

2022-11-27 19:12 UTC, Jinwoo-1162 commented
If there are any places where width, height, margins, etc are defined with px, those should be changed to relative units. px are useful for things like border thickness, border radius, etc

You can take a look at this blog post if you want to learn more: https://joseewouters.nl/blog/the-magic-of-relative-units/

2022-11-28 01:39 UTC, Jinwoo-1162 approved these changes

2022-11-28 01:39 UTC, merged